using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ReswPlusUnitTests;

/// <summary>
/// Writes the C# of a plural provider from the rules CLDR publishes.
/// </summary>
/// <remarks>
/// The providers ReswPlus ships are written by hand. This writes the same thing from the rules themselves, so
/// that the two can be compared: what it produces has to compile, and has to decide every quantity the way the
/// hand written provider does. It exists to answer whether the providers could be generated at all, not to
/// replace them.
/// </remarks>
internal static class CldrEmitter
{
    /// <summary>
    /// The operands, in the order they are declared, and the expression each is read with.
    /// </summary>
    /// <remarks>
    /// A <see cref="double"/> carries no trailing zeros, so the operands that count the decimals with them and
    /// the operands that count them without come out equal. <c>c</c> and <c>e</c> are the exponent of a compact
    /// notation, which a quantity never arrives here carrying.
    /// </remarks>
    private static readonly (char Operand, string Expression)[] Operands =
    [
        ('i', "System.Math.Truncate(n)"),
        ('v', "n.GetNumberOfDigitsAfterDecimal()"),
        ('w', "n.GetNumberOfDigitsAfterDecimal()"),
        ('f', "n.DigitsAfterDecimal()"),
        ('t', "n.DigitsAfterDecimal()"),
        ('c', "0"),
        ('e', "0"),
    ];

    /// <summary>
    /// Writes the provider of a set of rules.
    /// </summary>
    /// <param name="className">The name to give the class.</param>
    /// <param name="rules">The rules, in the order CLDR publishes them.</param>
    /// <returns>The source of a provider implementing them.</returns>
    public static string Emit(string className, IReadOnlyList<CldrPublishedRules.Rule> rules)
    {
        var used = new HashSet<char>();
        var conditions = new List<(string Category, string Condition, string Source)>();

        foreach (var rule in rules)
        {
            if (rule.Condition.Length == 0)
            {
                continue;
            }

            var parsed = CldrRule.Parse(rule.Condition);
            parsed.CollectOperands(used);
            conditions.Add((rule.Category, parsed.ToCSharp(), rule.Condition));
        }

        var source = new StringBuilder();

        source.AppendLine("using _ReswPlus_AutoGenerated.Utils;");
        source.AppendLine();
        source.AppendLine("namespace _ReswPlus_AutoGenerated.Plurals");
        source.AppendLine("{");
        source.AppendLine(CultureInfo.InvariantCulture, $"    internal sealed class {className} : IPluralProvider");
        source.AppendLine("    {");
        source.AppendLine("        public PluralTypeEnum ComputePlural(double n)");
        source.AppendLine("        {");

        // Only the operands the rules read are declared, so that nothing is computed twice and nothing is
        // computed for nothing.
        foreach (var (operand, expression) in Operands.Where(candidate => used.Contains(candidate.Operand)))
        {
            source.AppendLine(CultureInfo.InvariantCulture, $"            double {operand} = {expression};");
        }

        if (used.Count != 0)
        {
            source.AppendLine();
        }

        foreach (var (category, condition, published) in conditions)
        {
            source.AppendLine(CultureInfo.InvariantCulture, $"            // {category.ToLowerInvariant()}: {published}");
            source.AppendLine(CultureInfo.InvariantCulture, $"            if ({condition})");
            source.AppendLine("            {");
            source.AppendLine(CultureInfo.InvariantCulture, $"                return PluralTypeEnum.{category};");
            source.AppendLine("            }");
            source.AppendLine();
        }

        source.AppendLine("            return PluralTypeEnum.OTHER;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }
}
