using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Xunit;

namespace ReswPlusUnitTests;

/// <summary>
/// Tests covering the hygiene of the code emitted by the generator: the auto-generated header and the XML
/// documentation, both of which are required for the generated code to build
/// cleanly in projects with analyzers and warnings-as-errors enabled.
/// </summary>
public class GeneratedCodeHygiene
{
    private static string GenerateSample()
    {
        return ReswTestHelpers.GenerateCode(ReswTestHelpers.CreateResw(
            ("Welcome", "Welcome!", null),
            ("HtmlString", "Click <b>here</b> & win", null),
            ("Greeting", "Hello {0}, you are {1} years old", "#Format[String name, Int age]"),
            ("WithMacro", "Running {0}", "#Format[APP_NAME]"),
            ("FileCount_None", "No files", null),
            ("FileCount_One", "{0} file", "#Format[Plural Int count]"),
            ("FileCount_Other", "{0} files", "#Format[Plural Int count]"),
            ("Theme_Variant0", "Light theme", null),
            ("Theme_Variant1", "Dark theme", null)));
    }

    [Fact]
    public void GeneratedFileStartsWithAutoGeneratedMarker()
    {
        var code = GenerateSample();

        // Many analyzers only inspect the very first line of a file to decide whether it is generated code.
        Assert.StartsWith("// <auto-generated/>\r\n", code);
    }

    [Fact]
    public void GeneratedFileUsesTheGeneratedCodeExtension()
    {
        var file = ReswTestHelpers.GenerateFile(ReswTestHelpers.CreateResw(("Welcome", "Welcome!", null)));

        // Tooling also recognizes generated code by its file name, not just by the header.
        Assert.EndsWith(".g.cs", file.Filename);
    }

    [Fact]
    public void GeneratedFileIsValidForAProjectWithoutNullableReferenceTypes()
    {
        // Projects created from the UWP templates default to C# 7.3, so the generated code stays within it: it
        // relies on the <auto-generated/> marker to keep the consumer's nullable analysis off its output rather
        // than on a nullable context of its own, which would need C# 8.
        var code = GenerateSample();

        Assert.DoesNotContain("#nullable", code);

        var options = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp7_3);
        var diagnostics = CSharpSyntaxTree.ParseText(code, options).GetDiagnostics().ToArray();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public void GeneratedFileIsSyntacticallyValid()
    {
        var code = GenerateSample();

        var diagnostics = CSharpSyntaxTree.ParseText(code).GetDiagnostics().ToArray();

        Assert.Empty(diagnostics);
    }

    [Fact]
    public void EveryVisibleMemberIsDocumented()
    {
        var root = CSharpSyntaxTree.ParseText(GenerateSample()).GetRoot();

        var visibleMembers = root.DescendantNodes()
            .OfType<MemberDeclarationSyntax>()
            .Where(member => member is EnumMemberDeclarationSyntax ||
                             member.Modifiers.Any(SyntaxKind.PublicKeyword) ||
                             member.Modifiers.Any(SyntaxKind.ProtectedKeyword))
            .ToArray();

        Assert.NotEmpty(visibleMembers);

        foreach (var member in visibleMembers)
        {
            // A visible member without documentation is reported as CS1591 when the consuming project
            // sets GenerateDocumentationFile.
            Assert.True(
                GetDocumentation(member) is not null,
                $"Missing documentation on: {member.ToString().Split('\n')[0].Trim()}");
        }
    }

    [Fact]
    public void EveryParameterOfADocumentedMethodIsDocumented()
    {
        var root = CSharpSyntaxTree.ParseText(GenerateSample()).GetRoot();

        var methods = root.DescendantNodes().OfType<MethodDeclarationSyntax>().ToArray();

        Assert.NotEmpty(methods);

        foreach (var method in methods)
        {
            var documentation = GetDocumentation(method);

            Assert.NotNull(documentation);

            var documentedParameters = documentation!
                .DescendantNodes()
                .OfType<XmlElementSyntax>()
                .Where(element => element.StartTag.Name.LocalName.Text == "param")
                .SelectMany(element => element.StartTag.Attributes.OfType<XmlNameAttributeSyntax>())
                .Select(attribute => attribute.Identifier.Identifier.Text)
                .ToArray();

            foreach (var parameter in method.ParameterList.Parameters)
            {
                // A documented member that omits one of its parameters is reported as CS1573.
                Assert.Contains(parameter.Identifier.Text, documentedParameters);
            }
        }
    }

    [Fact]
    public void ResourceValuesAreEscapedInTheDocumentation()
    {
        var code = GenerateSample();

        // A resource value containing markup would produce invalid XML documentation (CS1570) if left unescaped.
        Assert.Contains("Click &lt;b&gt;here&lt;/b&gt; &amp; win", code);
        Assert.DoesNotContain("Click <b>here</b> & win", code);
    }

    [Fact]
    public void MarkupExtensionPropertiesAreNotAnnotatedForNullability()
    {
        var code = GenerateSample();

        // Annotating them would need C# 8, which projects created from the UWP templates don't use by default.
        // The <auto-generated/> marker keeps the consumer's nullable analysis off the file instead.
        Assert.Contains("public IValueConverter Converter", code);
        Assert.Contains("public object ConverterParameter", code);
    }

    private static DocumentationCommentTriviaSyntax? GetDocumentation(SyntaxNode member)
    {
        return member.GetLeadingTrivia()
            .Select(trivia => trivia.GetStructure())
            .OfType<DocumentationCommentTriviaSyntax>()
            .FirstOrDefault();
    }
}
