using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using ReswPlus.SourceGenerator;

namespace ReswPlusUnitTests;

/// <summary>
/// Compiles the <c>ResourceLoaderExtension</c> template against a stub resource provider and runs it.
/// </summary>
/// <remarks>
/// The template is what decides which plural form of a resource is looked up and what happens when that form
/// isn't declared, and it is emitted verbatim, so it is compiled here rather than reimplemented.
/// </remarks>
internal sealed class ResourceLoaderExtensionHost
{
    /// <summary>
    /// A stand-in for the resource provider the generated code talks to, reading from the values a test sets.
    /// </summary>
    private const string ResourceStringProviderStub = """
        namespace _ReswPlus_AutoGenerated
        {
            internal sealed class ResourceStringProvider
            {
                public static System.Collections.Generic.Dictionary<string, string> Values;
                public static bool ThrowWhenMissing;

                public ResourceStringProvider(string resourceMapId)
                {
                }

                public string GetString(string resourceId)
                {
                    string value;
                    if (Values.TryGetValue(resourceId, out value))
                    {
                        return value;
                    }
                    if (ThrowWhenMissing)
                    {
                        throw new System.Collections.Generic.KeyNotFoundException(resourceId);
                    }
                    return "";
                }
            }
        }
        """;

    /// <summary>
    /// A stand-in for the Windows app runtime language list, so that the opted-in resolver compiles here.
    /// </summary>
    private const string ApplicationLanguagesStub = """
        namespace Windows.Globalization
        {
            internal static class ApplicationLanguages
            {
                public static global::System.Collections.Generic.IReadOnlyList<string> Languages { get; set; }
                    = new string[0];
            }
        }
        """;

    private readonly Type _extensionType;
    private readonly Type _providerType;
    private readonly Type _applicationLanguagesType;
    private readonly object _provider;

    private ResourceLoaderExtensionHost(Assembly assembly)
    {
        _extensionType = assembly.GetType("_ReswPlus_AutoGenerated.Plurals.ResourceLoaderExtension")!;
        _providerType = assembly.GetType("_ReswPlus_AutoGenerated.ResourceStringProvider")!;
        _applicationLanguagesType = assembly.GetType("Windows.Globalization.ApplicationLanguages")!;
        _provider = Activator.CreateInstance(_providerType, "Resources")!;
    }

    /// <summary>
    /// Sets the app runtime language list the generated code sees.
    /// </summary>
    /// <param name="languages">The languages, most preferred first.</param>
    public void SetApplicationLanguages(params string[] languages)
    {
        _applicationLanguagesType.GetProperty("Languages")!.SetValue(null, languages);
    }

    /// <summary>
    /// Builds a host whose plural rules are the ones of the given language.
    /// </summary>
    /// <param name="language">The language whose plural rules the generated selector should return.</param>
    /// <param name="providerId">The identifier of the provider holding those rules.</param>
    /// <returns>A host running a freshly compiled copy of the template.</returns>
    /// <remarks>
    /// Every host gets its own assembly, because the template caches the provider it resolved in a static
    /// field on first use and never revisits it.
    /// </remarks>
    public static ResourceLoaderExtensionHost Create(string language, string providerId, bool useApplicationLanguages = false)
    {
        return Create([(language, providerId)], useApplicationLanguages);
    }

    /// <summary>
    /// Builds a host that knows the plural rules of several languages.
    /// </summary>
    /// <param name="rules">The provider holding the rules of each language.</param>
    /// <param name="useApplicationLanguages">Whether the language should come from the app runtime language list.</param>
    /// <returns>A host running a freshly compiled copy of the template.</returns>
    public static ResourceLoaderExtensionHost Create(
        IReadOnlyList<(string Language, string ProviderId)> rules,
        bool useApplicationLanguages = false)
    {
        var selector = string.Concat(rules.Select(rule =>
            $"case \"{rule.Language}\":\n" +
            $"  return new _ReswPlus_AutoGenerated.Plurals.{rule.ProviderId}Provider();\n")) +
            "default:\n" +
            "  return new _ReswPlus_AutoGenerated.Plurals.OtherProvider();\n";

        var resourceLoaderExtension = PluralTemplates.Read("Plurals.ResourceLoaderExtension")
            .Replace("{{PluralProviderSelector}}", selector)
            .Replace("{{PluralLanguageResolver}}", PluralLanguageResolvers.GetResolver(useApplicationLanguages));

        var sources = new[]
        {
            PluralTemplates.Read("Plurals.IPluralProvider"),
            PluralTemplates.Read("Plurals.PluralTypeEnum"),
            PluralTemplates.Read("Utils.IntExt"),
            PluralTemplates.Read("Utils.DoubleExt"),
            PluralTemplates.Read("Plurals.OtherProvider"),
            resourceLoaderExtension,
            ResourceStringProviderStub,
            ApplicationLanguagesStub
        }.Concat(rules.Select(rule => PluralTemplates.Read($"Plurals.{rule.ProviderId}Provider")));

        var assemblyName = $"ReswPlusLoader.{string.Join(".", rules.Select(rule => rule.ProviderId))}";

        return new ResourceLoaderExtensionHost(PluralTemplates.Compile(assemblyName, sources.Distinct()));
    }

    /// <summary>
    /// Looks up a pluralized resource, against the given resource set.
    /// </summary>
    /// <param name="values">The resources that are declared, keyed by their full name.</param>
    /// <param name="key">The key of the pluralized resource.</param>
    /// <param name="number">The quantity to select a form for.</param>
    /// <param name="supportNoneState">Whether the resource declares an empty state.</param>
    /// <param name="throwWhenMissing">Whether a lookup of an undeclared resource throws instead of returning "".</param>
    /// <returns>The string the generated code would render.</returns>
    public string GetPlural(
        IDictionary<string, string> values,
        string key,
        double number,
        bool supportNoneState = false,
        bool throwWhenMissing = false)
    {
        _providerType.GetField("Values")!.SetValue(null, new Dictionary<string, string>(values));
        _providerType.GetField("ThrowWhenMissing")!.SetValue(null, throwWhenMissing);

        var getPlural = _extensionType.GetMethod("GetPlural", BindingFlags.Public | BindingFlags.Static)!;

        return (string)getPlural.Invoke(null, [_provider, key, number, supportNoneState])!;
    }

    /// <summary>
    /// Runs an action with the UI culture the generated code reads its plural language from.
    /// </summary>
    public static void WithUICulture(string language, Action action)
    {
        var previous = CultureInfo.CurrentUICulture;
        CultureInfo.CurrentUICulture = new CultureInfo(language);
        try
        {
            action();
        }
        finally
        {
            CultureInfo.CurrentUICulture = previous;
        }
    }
}

/// <summary>
/// Reads and compiles the templates embedded in the generator.
/// </summary>
internal static class PluralTemplates
{
    private const string TemplateNamespace = "ReswPlus.SourceGenerator.Templates";

    /// <summary>
    /// Reads a template out of the embedded resources of the generator.
    /// </summary>
    /// <param name="name">The name of the template, relative to the templates folder and without extension.</param>
    /// <returns>The content of the template.</returns>
    public static string Read(string name)
    {
        var resourceName = $"{TemplateNamespace}.{name}.txt";
        var assembly = typeof(ReswPlus.SourceGenerator.ReswSourceGenerator).Assembly;

        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"The generator doesn't embed a '{resourceName}' template.");

        using var reader = new StreamReader(stream);

        return reader.ReadToEnd();
    }

    /// <summary>
    /// Compiles a set of templates into an in-memory assembly.
    /// </summary>
    /// <param name="assemblyName">The name to give the compiled assembly.</param>
    /// <param name="sources">The sources to compile.</param>
    /// <returns>The compiled assembly.</returns>
    public static Assembly Compile(string assemblyName, IEnumerable<string> sources)
    {
        var compilation = CSharpCompilation.Create(
            assemblyName,
            sources.Select(source => CSharpSyntaxTree.ParseText(source)),
            GetRuntimeReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        using var peStream = new MemoryStream();

        var result = compilation.Emit(peStream);

        if (!result.Success)
        {
            var errors = result.Diagnostics.Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);

            throw new InvalidOperationException(
                $"The templates of '{assemblyName}' do not compile:{Environment.NewLine}" +
                string.Join(Environment.NewLine, errors));
        }

        return Assembly.Load(peStream.ToArray());
    }

    private static IEnumerable<MetadataReference> GetRuntimeReferences()
    {
        var trustedAssemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;

        return trustedAssemblies
            .Split(Path.PathSeparator)
            .Where(path => path.Length > 0)
            .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path));
    }
}
