<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReswPlusUnitTests" />
    <PackageReference Include="Microsoft.Build.Framework" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" />
  </ItemGroup>

</Project>
