using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;

namespace CldrRuleImporter;

/// <summary>
/// Turns the plural rules Unicode CLDR publishes into the C# the generator holds them as.
/// </summary>
/// <remarks>
/// Everything that has to be worked out from the rules is worked out here, once, and written down: which
/// languages share a set of rules, what to call the class implementing them, which categories a translator has
/// to supply, and the source of the class itself. The generator is left with a table to look up, so nothing
/// about reading CLDR's file or its rule syntax is loaded into Visual Studio.
/// <para>
/// Run it with <c>dotnet run --project tools/CldrRuleImporter</c>. It rewrites
/// <c>src/ReswPlus.SourceGenerator/Plurals/CldrPluralRules.g.cs</c>, which is checked in and reviewed like any
/// other change: a CLDR release shows up as the rules that actually moved.
/// </para>
/// </remarks>
internal static class Program
{
    private const string Source =
        "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-core/supplemental/plurals.json";

    private static int Main(string[] args)
    {
        try
        {
            var root = FindRepositoryRoot();
            var vendored = Path.Combine(root, "tools", "CldrRuleImporter", "plurals.json");
            var output = Path.Combine(root, "src", "ReswPlus.SourceGenerator", "Plurals", "CldrPluralRules.g.cs");

            if (args.Contains("--download"))
            {
                Download(vendored);
            }

            Console.WriteLine($"Reading {vendored}");

            var json = File.ReadAllText(vendored);
            var rules = CldrPublishedRules.Read(json);
            var forms = CldrPluralForm.Create(rules.Cardinal);

            File.WriteAllText(output, Emit(rules.Version, forms), new UTF8Encoding(false));

            Console.WriteLine(
                $"Wrote {forms.Count} sets of rules for {forms.Sum(form => form.Languages.Count)} languages " +
                $"from CLDR {rules.Version} to {output}");

            return 0;
        }
        catch (Exception error)
        {
            Console.Error.WriteLine($"Error: {error.Message}");

            return 1;
        }
    }

    private static void Download(string destination)
    {
        Console.WriteLine($"Reading {Source}");

        using var client = new HttpClient();

        // Written as bytes so the copy is what was published, byte for byte.
        File.WriteAllBytes(destination, client.GetByteArrayAsync(Source).GetAwaiter().GetResult());
    }

    /// <summary>
    /// Writes the table the generator reads.
    /// </summary>
    private static string Emit(string version, IReadOnlyList<CldrPluralForm> forms)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine("// Generated by tools/CldrRuleImporter from the plural rules of Unicode CLDR.");
        source.AppendLine("// Run: dotnet run --project tools/CldrRuleImporter");
        source.AppendLine("// Do not edit by hand.");
        source.AppendLine();
        source.AppendLine("using ReswPlus.SourceGenerator.ClassGenerators;");
        source.AppendLine();
        source.AppendLine("namespace ReswPlus.SourceGenerator.Plurals;");
        source.AppendLine();
        source.AppendLine("/// <summary>");
        source.AppendLine("/// The plural rules of Unicode CLDR, as the classes implementing them.");
        source.AppendLine("/// </summary>");
        source.AppendLine("/// <remarks>");
        source.AppendLine("/// Each entry is one set of rules, the languages CLDR gives it to, and the source of the class that");
        source.AppendLine("/// decides a quantity by them. Languages sharing a set of rules share an entry, so a project gets one");
        source.AppendLine("/// class per set of rules its languages use rather than one per language.");
        source.AppendLine("/// </remarks>");
        source.AppendLine("internal static class CldrPluralRules");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// The CLDR release these rules were published in.");
        source.AppendLine("    /// </summary>");
        source.AppendLine($"    public const string Version = {Quote(version)};");
        source.AppendLine();
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Every set of rules CLDR publishes.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    public static readonly CldrPluralForm[] Forms =");
        source.AppendLine("    [");

        foreach (var form in forms)
        {
            source.AppendLine($"        // {string.Join(", ", form.Languages)}");
            source.AppendLine("        new(");
            source.AppendLine($"            {Quote(form.Id)},");
            source.AppendLine($"            [{string.Join(", ", form.Languages.Select(Quote))}],");
            source.AppendLine($"            [{string.Join(", ", form.Categories.Select(Category))}],");
            source.AppendLine($"            [{string.Join(", ", form.OptionalCategories.Select(Category))}],");
            source.AppendLine($"            {(form.ZeroIsOnlyForZeroQuantity ? "true" : "false")},");
            source.AppendLine("            \"\"\"");
            source.Append(Indent(CldrEmitter.Emit(form.Id + "Provider", form.Rules, form.Languages, version), "            "));
            source.AppendLine("            \"\"\"),");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string Indent(string text, string indent)
    {
        var lines = text.Replace("\r\n", "\n").TrimEnd('\n').Split('\n');

        return string.Concat(lines.Select(line => line.Length == 0 ? "\n" : indent + line + "\n"));
    }

    private static string Category(string category)
    {
        return "PluralCategory." + category[0] + category.Substring(1).ToLowerInvariant();
    }

    private static string Quote(string value)
    {
        return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !Directory.Exists(Path.Combine(directory.FullName, ".git")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("The repository root could not be found.");
    }
}
