namespace TestCppWinRT
{
    namespace Strings
    {
        static runtimeclass Resources
        {
            static String YouGotEmails(UInt32 numberMessages, String username);
            static String GotMessagesFrom(UInt32 numberMessages, Int64 personalPronoun);
            static String SendMessage(Int64 variantId);
            static String YouGotEmailsDotNet(UInt32 numberMessages, String username);
            static String Hello{ get; };
            static String TestWithObject(Windows.Foundation.IStringable obj);
            static String TestFormatWithLiteralString{ get; };
            static String TestFormatWithLocalizationRef{ get; };
            static String TestFormatWithMacro{ get; };
        };

        enum KeyEnum
        {
            __Undefined = 0,
            YouGotEmails,
            GotMessagesFrom,
            SendMessage,
            YouGotEmailsDotNet,
            Hello,
            TestWithObject,
            TestFormatWithLiteralString,
            TestFormatWithLocalizationRef,
            TestFormatWithMacro,
        };

        runtimeclass ResourcesExtension: Windows.UI.Xaml.Markup.MarkupExtension
        {
            ResourcesExtension();
            KeyEnum Key;
            Windows.UI.Xaml.Data.IValueConverter Converter;
            Object ConverterParameter;
            overridable Object ProvideValue();
        };
    } // namespace Strings
} // namespace TestCppWinRT
