// File generated automatically by ReswPlus. https://github.com/rudyhuyn/ReswPlus
// The NuGet package ReswPlusLib is necessary to support Pluralization.
#pragma once

namespace TestCppCX
{
    namespace Strings
    {
        public ref class Resources sealed
        {
        private:
            static Windows::ApplicationModel::Resources::ResourceLoader^ _resourceLoader;
            static Windows::ApplicationModel::Resources::ResourceLoader^ GetResourceLoader();
        public:
            Resources() {}

        /* Methods and properties for GotMessagesFrom */
        public:
            /// <summary>
            ///   Get the pluralized version of the string similar to: You got %d message from her
            /// </summary>
            static Platform::String^ GotMessagesFrom(unsigned int numberMessages, long long personalPronoun);

        /* Methods and properties for SendMessage */
        public:
            /// <summary>
            ///   Get the variant version of the string similar to: Send her a message
            /// </summary>
            static Platform::String^ SendMessage(int variantId);

        /* Methods and properties for YouGotEmailsDotNet */
        public:
            /// <summary>
            ///   Get the pluralized version of the string similar to: Hello {1}, you got {0:F0} email (DotNet formatting)
            /// </summary>
            static Platform::String^ YouGotEmailsDotNet(unsigned int numberMessages, Platform::String^ username);

        /* Methods and properties for YouGotEmails */
        public:
            /// <summary>
            ///   Get the pluralized version of the string similar to: Hello %2$ls, you got %1$u email
            /// </summary>
            static Platform::String^ YouGotEmails(unsigned int numberMessages, Platform::String^ username);

        /* Methods and properties for Hello */
        public:
            /// <summary>
            ///   Looks up a localized string similar to: Hello world
            /// </summary>
            static property Platform::String^ Hello
            {
                Platform::String^ get();
            }

        /* Methods and properties for TestFormatWithLiteralString */
        public:
            /// <summary>
            ///   Looks up a localized string similar to: This '%ls' is a literal string
            /// </summary>
            static property Platform::String^ TestFormatWithLiteralString
            {
                Platform::String^ get();
            }

        /* Methods and properties for TestFormatWithLocalizationRef */
        public:
            /// <summary>
            ///   Looks up a localized string similar to: This '%ls' is a localization ref
            /// </summary>
            static property Platform::String^ TestFormatWithLocalizationRef
            {
                Platform::String^ get();
            }

        /* Methods and properties for TestFormatWithMacro */
        public:
            /// <summary>
            ///   Looks up a localized string similar to: These '{0}', '{1}', '{2}' are string generated by a macros
            /// </summary>
            static property Platform::String^ TestFormatWithMacro
            {
                Platform::String^ get();
            }

        /* Methods and properties for TestWithObject */
        public:
            /// <summary>
            ///   Looks up a localized string similar to: Test with object %s
            /// </summary>
            static Platform::String^ TestWithObject(Platform::Object^ obj);
        };

        public enum class KeyEnum
        {
            __Undefined = 0,
            GotMessagesFrom,
            SendMessage,
            YouGotEmailsDotNet,
            YouGotEmails,
            Hello,
            TestFormatWithLiteralString,
            TestFormatWithLocalizationRef,
            TestFormatWithMacro,
            TestWithObject,
        };

        public ref class ResourcesExtension sealed: public Windows::UI::Xaml::Markup::MarkupExtension
        {
        private:
            Windows::ApplicationModel::Resources::ResourceLoader^ _resourceLoader;
        public:
            ResourcesExtension();
            property KeyEnum Key;
            property Windows::UI::Xaml::Data::IValueConverter^ Converter;
            property Platform::Object^ ConverterParameter;
        protected:
            virtual Platform::Object^ ProvideValue() override;
    };
} // namespace Strings
} // namespace TestCppCX
