namespace ReswPlus.SourceGenerator.CodeGenerators;

/// <summary>
/// Defines the conventions shared by every file emitted by ReswPlus.
/// </summary>
internal static class GeneratedCode
{
    /// <summary>
    /// The header prepended to every emitted file, terminated by a blank line.
    /// </summary>
    /// <remarks>
    /// The <c>&lt;auto-generated/&gt;</c> marker on the very first line is how Roslyn, StyleCop and most third
    /// party analyzers detect generated code. Analyzers skip generated code by default, and the compiler skips
    /// its own nullable analysis for it, so the marker keeps the emitted output out of the consumer's build
    /// results without the code having to declare a nullable context of its own.
    /// </remarks>
    public const string FileHeader =
        "// <auto-generated/>\r\n" +
        "// File generated automatically by ReswPlus. https://github.com/DotNetPlus/ReswPlus\r\n" +
        "\r\n";

    /// <summary>
    /// The extension used for the hint name of every emitted file.
    /// </summary>
    /// <remarks>
    /// On top of the <c>&lt;auto-generated/&gt;</c> marker in <see cref="FileHeader"/>, tooling also recognizes
    /// generated code by its file name. Roslyn's own generated code detection, StyleCop and most code coverage
    /// tools all treat a file whose name ends with <c>.g.cs</c> as generated.
    /// </remarks>
    public const string FileExtension = ".g.cs";

    /// <summary>
    /// Prepends <see cref="FileHeader"/> to the given source code.
    /// </summary>
    /// <param name="sourceCode">The source code to prepend the header to.</param>
    /// <returns>The source code, preceded by the generated file header.</returns>
    public static string AddFileHeader(string sourceCode)
    {
        return FileHeader + sourceCode;
    }
}
