// <auto-generated/>
// Generated by tools/CldrRuleImporter from the plural rules of Unicode CLDR.
// Run: dotnet run --project tools/CldrRuleImporter
// Do not edit by hand.

using ReswPlus.SourceGenerator.ClassGenerators;

namespace ReswPlus.SourceGenerator.Plurals;

/// <summary>
/// The plural rules of Unicode CLDR, as the classes implementing them.
/// </summary>
/// <remarks>
/// Each entry is one set of rules and the languages CLDR gives it to. Languages sharing a set of rules
/// share an entry, so a project gets one class per set of rules its languages use rather than one per
/// language. The rules are held as the objects they are made of; the code deciding them is written by
/// <see cref="CldrEmitter"/> when a project is generated.
/// </remarks>
internal static class CldrPluralRules
{
    /// <summary>
    /// The CLDR release these rules were published in.
    /// </summary>
    public const string Version = "48";

    /// <summary>
    /// Every set of rules CLDR publishes.
    /// </summary>
    public static readonly CldrPluralForm[] Forms =
    [
        // af, an, asa, ast, az, bal, bem, bez, bg, brx, ce, cgg, chr, ckb, de, dv, ee, el, en, eo, et, eu, fi, fo, fur, fy, gl, gsw, ha, haw, hu, ia, ie, io, jgo, ji, jmc, ka, kaj, kcg, kk, kkj, kl, ks, ksb, ku, ky, lb, lg, lij, mas, mgo, ml, mn, mr, nah, nb, nd, ne, nl, nn, nnh, no, nr, ny, nyn, om, or, os, pap, ps, rm, rof, rwk, saq, sc, sd, sdh, seh, sn, so, sq, ss, ssy, st, sv, sw, syr, ta, te, teo, tig, tk, tn, tr, ts, ug, ur, uz, ve, vo, vun, wae, xh, xog, yi
        new(
            "Af",
            ["af", "an", "asa", "ast", "az", "bal", "bem", "bez", "bg", "brx", "ce", "cgg", "chr", "ckb", "de", "dv", "ee", "el", "en", "eo", "et", "eu", "fi", "fo", "fur", "fy", "gl", "gsw", "ha", "haw", "hu", "ia", "ie", "io", "jgo", "ji", "jmc", "ka", "kaj", "kcg", "kk", "kkj", "kl", "ks", "ksb", "ku", "ky", "lb", "lg", "lij", "mas", "mgo", "ml", "mn", "mr", "nah", "nb", "nd", "ne", "nl", "nn", "nnh", "no", "nr", "ny", "nyn", "om", "or", "os", "pap", "ps", "rm", "rof", "rwk", "saq", "sc", "sd", "sdh", "seh", "sn", "so", "sq", "ss", "ssy", "st", "sv", "sw", "syr", "ta", "te", "teo", "tig", "tk", "tn", "tr", "ts", "ug", "ur", "uz", "ve", "vo", "vun", "wae", "xh", "xog", "yi"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("OTHER", "", null),
            ]),
        // ak, bh, bho, csw, guw, ln, mg, nso, pa, ti, wa
        new(
            "Ak",
            ["ak", "bh", "bho", "csw", "guw", "ln", "mg", "nso", "pa", "ti", "wa"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 0..1", new CldrRelation('n', 0, false, [new(0, 1)])),
                new("OTHER", "", null),
            ]),
        // am, as, bn, doi, fa, gu, hi, kn, kok, kok-Latn, pcm, zu
        new(
            "Am",
            ["am", "as", "bn", "doi", "fa", "gu", "hi", "kn", "kok", "kok-Latn", "pcm", "zu"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 0 or n = 1", new CldrAnyOf([new CldrRelation('i', 0, false, [new(0, 0)]), new CldrRelation('n', 0, false, [new(1, 1)])])),
                new("OTHER", "", null),
            ]),
        // ar, ars
        new(
            "Ar",
            ["ar", "ars"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ZERO", "n = 0", new CldrRelation('n', 0, false, [new(0, 0)])),
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("FEW", "n % 100 = 3..10", new CldrRelation('n', 100, false, [new(3, 10)])),
                new("MANY", "n % 100 = 11..99", new CldrRelation('n', 100, false, [new(11, 99)])),
                new("OTHER", "", null),
            ]),
        // be, ru, uk
        new(
            "Be",
            ["be", "ru", "uk"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n % 10 = 1 and n % 100 != 11", new CldrAllOf([new CldrRelation('n', 10, false, [new(1, 1)]), new CldrRelation('n', 100, true, [new(11, 11)])])),
                new("FEW", "n % 10 = 2..4 and n % 100 != 12..14", new CldrAllOf([new CldrRelation('n', 10, false, [new(2, 4)]), new CldrRelation('n', 100, true, [new(12, 14)])])),
                new("MANY", "n % 10 = 0 or n % 10 = 5..9 or n % 100 = 11..14", new CldrAnyOf([new CldrRelation('n', 10, false, [new(0, 0)]), new CldrRelation('n', 10, false, [new(5, 9)]), new CldrRelation('n', 100, false, [new(11, 14)])])),
                new("OTHER", "", null),
            ]),
        // blo, cv, ksh
        new(
            "Blo",
            ["blo", "cv", "ksh"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ZERO", "n = 0", new CldrRelation('n', 0, false, [new(0, 0)])),
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("OTHER", "", null),
            ]),
        // bm, bo, dz, hnj, id, ig, ii, in, ja, jbo, jv, jw, kde, kea, km, ko, lkt, lo, ms, my, nqo, osa, sah, ses, sg, su, th, to, tpi, und, vi, wo, yo, yue, zh
        new(
            "Bm",
            ["bm", "bo", "dz", "hnj", "id", "ig", "ii", "in", "ja", "jbo", "jv", "jw", "kde", "kea", "km", "ko", "lkt", "lo", "ms", "my", "nqo", "osa", "sah", "ses", "sg", "su", "th", "to", "tpi", "und", "vi", "wo", "yo", "yue", "zh"],
            [PluralCategory.Other],
            [],
            true,
            [
                new("OTHER", "", null),
            ]),
        // br
        new(
            "Br",
            ["br"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            [
                new("ONE", "n % 10 = 1 and n % 100 != 11,71,91", new CldrAllOf([new CldrRelation('n', 10, false, [new(1, 1)]), new CldrRelation('n', 100, true, [new(11, 11), new(71, 71), new(91, 91)])])),
                new("TWO", "n % 10 = 2 and n % 100 != 12,72,92", new CldrAllOf([new CldrRelation('n', 10, false, [new(2, 2)]), new CldrRelation('n', 100, true, [new(12, 12), new(72, 72), new(92, 92)])])),
                new("FEW", "n % 10 = 3..4,9 and n % 100 != 10..19,70..79,90..99", new CldrAllOf([new CldrRelation('n', 10, false, [new(3, 4), new(9, 9)]), new CldrRelation('n', 100, true, [new(10, 19), new(70, 79), new(90, 99)])])),
                new("MANY", "n != 0 and n % 1000000 = 0", new CldrAllOf([new CldrRelation('n', 0, true, [new(0, 0)]), new CldrRelation('n', 1000000, false, [new(0, 0)])])),
                new("OTHER", "", null),
            ]),
        // bs, hr, sh, sr
        new(
            "Bs",
            ["bs", "hr", "sh", "sr"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(1, 1)]), new CldrRelation('i', 100, true, [new(11, 11)])]), new CldrAllOf([new CldrRelation('f', 10, false, [new(1, 1)]), new CldrRelation('f', 100, true, [new(11, 11)])])])),
                new("FEW", "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 or f % 10 = 2..4 and f % 100 != 12..14", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(2, 4)]), new CldrRelation('i', 100, true, [new(12, 14)])]), new CldrAllOf([new CldrRelation('f', 10, false, [new(2, 4)]), new CldrRelation('f', 100, true, [new(12, 14)])])])),
                new("OTHER", "", null),
            ]),
        // ca, es, it, lld, pt-PT, scn, vec
        new(
            "Ca",
            ["ca", "es", "it", "lld", "pt-PT", "scn", "vec"],
            [PluralCategory.One, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            [
                new("ONE", "i = 1 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(1, 1)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("MANY", "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5", new CldrAnyOf([new CldrAllOf([new CldrRelation('e', 0, false, [new(0, 0)]), new CldrRelation('i', 0, true, [new(0, 0)]), new CldrRelation('i', 1000000, false, [new(0, 0)]), new CldrRelation('v', 0, false, [new(0, 0)])]), new CldrRelation('e', 0, true, [new(0, 5)])])),
                new("OTHER", "", null),
            ]),
        // ceb, fil, tl
        new(
            "Ceb",
            ["ceb", "fil", "tl"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "v = 0 and i = 1,2,3 or v = 0 and i % 10 != 4,6,9 or v != 0 and f % 10 != 4,6,9", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 0, false, [new(1, 1), new(2, 2), new(3, 3)])]), new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, true, [new(4, 4), new(6, 6), new(9, 9)])]), new CldrAllOf([new CldrRelation('v', 0, true, [new(0, 0)]), new CldrRelation('f', 10, true, [new(4, 4), new(6, 6), new(9, 9)])])])),
                new("OTHER", "", null),
            ]),
        // cs, sk
        new(
            "Cs",
            ["cs", "sk"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 1 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(1, 1)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("FEW", "i = 2..4 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(2, 4)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("MANY", "v != 0", new CldrRelation('v', 0, true, [new(0, 0)])),
                new("OTHER", "", null),
            ]),
        // cy
        new(
            "Cy",
            ["cy"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ZERO", "n = 0", new CldrRelation('n', 0, false, [new(0, 0)])),
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("FEW", "n = 3", new CldrRelation('n', 0, false, [new(3, 3)])),
                new("MANY", "n = 6", new CldrRelation('n', 0, false, [new(6, 6)])),
                new("OTHER", "", null),
            ]),
        // da
        new(
            "Da",
            ["da"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1 or t != 0 and i = 0,1", new CldrAnyOf([new CldrRelation('n', 0, false, [new(1, 1)]), new CldrAllOf([new CldrRelation('t', 0, true, [new(0, 0)]), new CldrRelation('i', 0, false, [new(0, 0), new(1, 1)])])])),
                new("OTHER", "", null),
            ]),
        // dsb, hsb
        new(
            "Dsb",
            ["dsb", "hsb"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "v = 0 and i % 100 = 1 or f % 100 = 1", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(1, 1)])]), new CldrRelation('f', 100, false, [new(1, 1)])])),
                new("TWO", "v = 0 and i % 100 = 2 or f % 100 = 2", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(2, 2)])]), new CldrRelation('f', 100, false, [new(2, 2)])])),
                new("FEW", "v = 0 and i % 100 = 3..4 or f % 100 = 3..4", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(3, 4)])]), new CldrRelation('f', 100, false, [new(3, 4)])])),
                new("OTHER", "", null),
            ]),
        // ff, hy, kab
        new(
            "Ff",
            ["ff", "hy", "kab"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 0,1", new CldrRelation('i', 0, false, [new(0, 0), new(1, 1)])),
                new("OTHER", "", null),
            ]),
        // fr, pt
        new(
            "Fr",
            ["fr", "pt"],
            [PluralCategory.One, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            [
                new("ONE", "i = 0,1", new CldrRelation('i', 0, false, [new(0, 0), new(1, 1)])),
                new("MANY", "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5", new CldrAnyOf([new CldrAllOf([new CldrRelation('e', 0, false, [new(0, 0)]), new CldrRelation('i', 0, true, [new(0, 0)]), new CldrRelation('i', 1000000, false, [new(0, 0)]), new CldrRelation('v', 0, false, [new(0, 0)])]), new CldrRelation('e', 0, true, [new(0, 5)])])),
                new("OTHER", "", null),
            ]),
        // ga
        new(
            "Ga",
            ["ga"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("FEW", "n = 3..6", new CldrRelation('n', 0, false, [new(3, 6)])),
                new("MANY", "n = 7..10", new CldrRelation('n', 0, false, [new(7, 10)])),
                new("OTHER", "", null),
            ]),
        // gd
        new(
            "Gd",
            ["gd"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1,11", new CldrRelation('n', 0, false, [new(1, 1), new(11, 11)])),
                new("TWO", "n = 2,12", new CldrRelation('n', 0, false, [new(2, 2), new(12, 12)])),
                new("FEW", "n = 3..10,13..19", new CldrRelation('n', 0, false, [new(3, 10), new(13, 19)])),
                new("OTHER", "", null),
            ]),
        // gv
        new(
            "Gv",
            ["gv"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "v = 0 and i % 10 = 1", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(1, 1)])])),
                new("TWO", "v = 0 and i % 10 = 2", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(2, 2)])])),
                new("FEW", "v = 0 and i % 100 = 0,20,40,60,80", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(0, 0), new(20, 20), new(40, 40), new(60, 60), new(80, 80)])])),
                new("MANY", "v != 0", new CldrRelation('v', 0, true, [new(0, 0)])),
                new("OTHER", "", null),
            ]),
        // he, iw
        new(
            "He",
            ["he", "iw"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 1 and v = 0 or i = 0 and v != 0", new CldrAnyOf([new CldrAllOf([new CldrRelation('i', 0, false, [new(1, 1)]), new CldrRelation('v', 0, false, [new(0, 0)])]), new CldrAllOf([new CldrRelation('i', 0, false, [new(0, 0)]), new CldrRelation('v', 0, true, [new(0, 0)])])])),
                new("TWO", "i = 2 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(2, 2)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("OTHER", "", null),
            ]),
        // is, mk
        new(
            "Is",
            ["is", "mk"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "t = 0 and i % 10 = 1 and i % 100 != 11 or t % 10 = 1 and t % 100 != 11", new CldrAnyOf([new CldrAllOf([new CldrRelation('t', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(1, 1)]), new CldrRelation('i', 100, true, [new(11, 11)])]), new CldrAllOf([new CldrRelation('t', 10, false, [new(1, 1)]), new CldrRelation('t', 100, true, [new(11, 11)])])])),
                new("OTHER", "", null),
            ]),
        // iu, naq, sat, se, sma, smi, smj, smn, sms
        new(
            "Iu",
            ["iu", "naq", "sat", "se", "sma", "smi", "smj", "smn", "sms"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("OTHER", "", null),
            ]),
        // kw
        new(
            "Kw",
            ["kw"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ZERO", "n = 0", new CldrRelation('n', 0, false, [new(0, 0)])),
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n % 100 = 2,22,42,62,82 or n % 1000 = 0 and n % 100000 = 1000..20000,40000,60000,80000 or n != 0 and n % 1000000 = 100000", new CldrAnyOf([new CldrRelation('n', 100, false, [new(2, 2), new(22, 22), new(42, 42), new(62, 62), new(82, 82)]), new CldrAllOf([new CldrRelation('n', 1000, false, [new(0, 0)]), new CldrRelation('n', 100000, false, [new(1000, 20000), new(40000, 40000), new(60000, 60000), new(80000, 80000)])]), new CldrAllOf([new CldrRelation('n', 0, true, [new(0, 0)]), new CldrRelation('n', 1000000, false, [new(100000, 100000)])])])),
                new("FEW", "n % 100 = 3,23,43,63,83", new CldrRelation('n', 100, false, [new(3, 3), new(23, 23), new(43, 43), new(63, 63), new(83, 83)])),
                new("MANY", "n != 1 and n % 100 = 1,21,41,61,81", new CldrAllOf([new CldrRelation('n', 0, true, [new(1, 1)]), new CldrRelation('n', 100, false, [new(1, 1), new(21, 21), new(41, 41), new(61, 61), new(81, 81)])])),
                new("OTHER", "", null),
            ]),
        // lag
        new(
            "Lag",
            ["lag"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ZERO", "n = 0", new CldrRelation('n', 0, false, [new(0, 0)])),
                new("ONE", "i = 0,1 and n != 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(0, 0), new(1, 1)]), new CldrRelation('n', 0, true, [new(0, 0)])])),
                new("OTHER", "", null),
            ]),
        // lt
        new(
            "Lt",
            ["lt"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n % 10 = 1 and n % 100 != 11..19", new CldrAllOf([new CldrRelation('n', 10, false, [new(1, 1)]), new CldrRelation('n', 100, true, [new(11, 19)])])),
                new("FEW", "n % 10 = 2..9 and n % 100 != 11..19", new CldrAllOf([new CldrRelation('n', 10, false, [new(2, 9)]), new CldrRelation('n', 100, true, [new(11, 19)])])),
                new("MANY", "f != 0", new CldrRelation('f', 0, true, [new(0, 0)])),
                new("OTHER", "", null),
            ]),
        // lv, prg
        new(
            "Lv",
            ["lv", "prg"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            false,
            [
                new("ZERO", "n % 10 = 0 or n % 100 = 11..19 or v = 2 and f % 100 = 11..19", new CldrAnyOf([new CldrRelation('n', 10, false, [new(0, 0)]), new CldrRelation('n', 100, false, [new(11, 19)]), new CldrAllOf([new CldrRelation('v', 0, false, [new(2, 2)]), new CldrRelation('f', 100, false, [new(11, 19)])])])),
                new("ONE", "n % 10 = 1 and n % 100 != 11 or v = 2 and f % 10 = 1 and f % 100 != 11 or v != 2 and f % 10 = 1", new CldrAnyOf([new CldrAllOf([new CldrRelation('n', 10, false, [new(1, 1)]), new CldrRelation('n', 100, true, [new(11, 11)])]), new CldrAllOf([new CldrRelation('v', 0, false, [new(2, 2)]), new CldrRelation('f', 10, false, [new(1, 1)]), new CldrRelation('f', 100, true, [new(11, 11)])]), new CldrAllOf([new CldrRelation('v', 0, true, [new(2, 2)]), new CldrRelation('f', 10, false, [new(1, 1)])])])),
                new("OTHER", "", null),
            ]),
        // mo, ro
        new(
            "Mo",
            ["mo", "ro"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 1 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(1, 1)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("FEW", "v != 0 or n = 0 or n != 1 and n % 100 = 1..19", new CldrAnyOf([new CldrRelation('v', 0, true, [new(0, 0)]), new CldrRelation('n', 0, false, [new(0, 0)]), new CldrAllOf([new CldrRelation('n', 0, true, [new(1, 1)]), new CldrRelation('n', 100, false, [new(1, 19)])])])),
                new("OTHER", "", null),
            ]),
        // mt
        new(
            "Mt",
            ["mt"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 1", new CldrRelation('n', 0, false, [new(1, 1)])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("FEW", "n = 0 or n % 100 = 3..10", new CldrAnyOf([new CldrRelation('n', 0, false, [new(0, 0)]), new CldrRelation('n', 100, false, [new(3, 10)])])),
                new("MANY", "n % 100 = 11..19", new CldrRelation('n', 100, false, [new(11, 19)])),
                new("OTHER", "", null),
            ]),
        // pl
        new(
            "Pl",
            ["pl"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 1 and v = 0", new CldrAllOf([new CldrRelation('i', 0, false, [new(1, 1)]), new CldrRelation('v', 0, false, [new(0, 0)])])),
                new("FEW", "v = 0 and i % 10 = 2..4 and i % 100 != 12..14", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(2, 4)]), new CldrRelation('i', 100, true, [new(12, 14)])])),
                new("MANY", "v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 0, true, [new(1, 1)]), new CldrRelation('i', 10, false, [new(0, 1)])]), new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 10, false, [new(5, 9)])]), new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(12, 14)])])])),
                new("OTHER", "", null),
            ]),
        // sgs
        new(
            "Sgs",
            ["sgs"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n % 10 = 1 and n % 100 != 11", new CldrAllOf([new CldrRelation('n', 10, false, [new(1, 1)]), new CldrRelation('n', 100, true, [new(11, 11)])])),
                new("TWO", "n = 2", new CldrRelation('n', 0, false, [new(2, 2)])),
                new("FEW", "n != 2 and n % 10 = 2..9 and n % 100 != 11..19", new CldrAllOf([new CldrRelation('n', 0, true, [new(2, 2)]), new CldrRelation('n', 10, false, [new(2, 9)]), new CldrRelation('n', 100, true, [new(11, 19)])])),
                new("MANY", "f != 0", new CldrRelation('f', 0, true, [new(0, 0)])),
                new("OTHER", "", null),
            ]),
        // shi
        new(
            "Shi",
            ["shi"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "i = 0 or n = 1", new CldrAnyOf([new CldrRelation('i', 0, false, [new(0, 0)]), new CldrRelation('n', 0, false, [new(1, 1)])])),
                new("FEW", "n = 2..10", new CldrRelation('n', 0, false, [new(2, 10)])),
                new("OTHER", "", null),
            ]),
        // si
        new(
            "Si",
            ["si"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 0,1 or i = 0 and f = 1", new CldrAnyOf([new CldrRelation('n', 0, false, [new(0, 0), new(1, 1)]), new CldrAllOf([new CldrRelation('i', 0, false, [new(0, 0)]), new CldrRelation('f', 0, false, [new(1, 1)])])])),
                new("OTHER", "", null),
            ]),
        // sl
        new(
            "Sl",
            ["sl"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "v = 0 and i % 100 = 1", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(1, 1)])])),
                new("TWO", "v = 0 and i % 100 = 2", new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(2, 2)])])),
                new("FEW", "v = 0 and i % 100 = 3..4 or v != 0", new CldrAnyOf([new CldrAllOf([new CldrRelation('v', 0, false, [new(0, 0)]), new CldrRelation('i', 100, false, [new(3, 4)])]), new CldrRelation('v', 0, true, [new(0, 0)])])),
                new("OTHER", "", null),
            ]),
        // tzm
        new(
            "Tzm",
            ["tzm"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            [
                new("ONE", "n = 0..1 or n = 11..99", new CldrAnyOf([new CldrRelation('n', 0, false, [new(0, 1)]), new CldrRelation('n', 0, false, [new(11, 99)])])),
                new("OTHER", "", null),
            ]),
    ];
}
