// <auto-generated/>
// Generated by tools/CldrRuleImporter from the plural rules of Unicode CLDR.
// Run: dotnet run --project tools/CldrRuleImporter
// Do not edit by hand.

using ReswPlus.SourceGenerator.ClassGenerators;

namespace ReswPlus.SourceGenerator.Plurals;

/// <summary>
/// The plural rules of Unicode CLDR, as the classes implementing them.
/// </summary>
/// <remarks>
/// Each entry is one set of rules, the languages CLDR gives it to, and the source of the class that
/// decides a quantity by them. Languages sharing a set of rules share an entry, so a project gets one
/// class per set of rules its languages use rather than one per language.
/// </remarks>
internal static class CldrPluralRules
{
    /// <summary>
    /// The CLDR release these rules were published in.
    /// </summary>
    public const string Version = "48";

    /// <summary>
    /// Every set of rules CLDR publishes.
    /// </summary>
    public static readonly CldrPluralForm[] Forms =
    [
        // af, an, asa, ast, az, bal, bem, bez, bg, brx, ce, cgg, chr, ckb, de, dv, ee, el, en, eo, et, eu, fi, fo, fur, fy, gl, gsw, ha, haw, hu, ia, ie, io, jgo, ji, jmc, ka, kaj, kcg, kk, kkj, kl, ks, ksb, ku, ky, lb, lg, lij, mas, mgo, ml, mn, mr, nah, nb, nd, ne, nl, nn, nnh, no, nr, ny, nyn, om, or, os, pap, ps, rm, rof, rwk, saq, sc, sd, sdh, seh, sn, so, sq, ss, ssy, st, sv, sw, syr, ta, te, teo, tig, tk, tn, tr, ts, ug, ur, uz, ve, vo, vun, wae, xh, xog, yi
        new(
            "Af",
            ["af", "an", "asa", "ast", "az", "bal", "bem", "bez", "bg", "brx", "ce", "cgg", "chr", "ckb", "de", "dv", "ee", "el", "en", "eo", "et", "eu", "fi", "fo", "fur", "fy", "gl", "gsw", "ha", "haw", "hu", "ia", "ie", "io", "jgo", "ji", "jmc", "ka", "kaj", "kcg", "kk", "kkj", "kl", "ks", "ksb", "ku", "ky", "lb", "lg", "lij", "mas", "mgo", "ml", "mn", "mr", "nah", "nb", "nd", "ne", "nl", "nn", "nnh", "no", "nr", "ny", "nyn", "om", "or", "os", "pap", "ps", "rm", "rof", "rwk", "saq", "sc", "sd", "sdh", "seh", "sn", "so", "sq", "ss", "ssy", "st", "sv", "sw", "syr", "ta", "te", "teo", "tig", "tk", "tn", "tr", "ts", "ug", "ur", "uz", "ve", "vo", "vun", "wae", "xh", "xog", "yi"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'af' and 105 other languages.</summary>
                /// <remarks>
                /// Shared by af, an, asa, ast, az, bal, bem, bez, bg, brx, ce, cgg, chr, ckb, de, dv, ee, el, en, eo, et, eu, fi, fo, fur, fy, gl, gsw, ha, haw, hu, ia, ie, io, jgo, ji, jmc, ka, kaj, kcg, kk, kkj, kl, ks, ksb, ku, ky, lb, lg, lij, mas, mgo, ml, mn, mr, nah, nb, nd, ne, nl, nn, nnh, no, nr, ny, nyn, om, or, os, pap, ps, rm, rof, rwk, saq, sc, sd, sdh, seh, sn, so, sq, ss, ssy, st, sv, sw, syr, ta, te, teo, tig, tk, tn, tr, ts, ug, ur, uz, ve, vo, vun, wae, xh, xog, yi.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class AfProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ak, bh, bho, csw, guw, ln, mg, nso, pa, ti, wa
        new(
            "Ak",
            ["ak", "bh", "bho", "csw", "guw", "ln", "mg", "nso", "pa", "ti", "wa"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ak' and 10 other languages.</summary>
                /// <remarks>
                /// Shared by ak, bh, bho, csw, guw, ln, mg, nso, pa, ti, wa.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class AkProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 0..1
                        if (n.IsInt() && n.IsBetween(0, 1))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // am, as, bn, doi, fa, gu, hi, kn, kok, kok-Latn, pcm, zu
        new(
            "Am",
            ["am", "as", "bn", "doi", "fa", "gu", "hi", "kn", "kok", "kok-Latn", "pcm", "zu"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'am' and 11 other languages.</summary>
                /// <remarks>
                /// Shared by am, as, bn, doi, fa, gu, hi, kn, kok, kok-Latn, pcm, zu.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class AmProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);

                        // one: i = 0 or n = 1
                        if (i == 0 || n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ar, ars
        new(
            "Ar",
            ["ar", "ars"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ar' and 1 other language.</summary>
                /// <remarks>
                /// Shared by ar, ars.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class ArProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // zero: n = 0
                        if (n == 0)
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n % 100 = 3..10
                        if ((n % 100).IsInt() && (n % 100).IsBetween(3, 10))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n % 100 = 11..99
                        if ((n % 100).IsInt() && (n % 100).IsBetween(11, 99))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // be, ru, uk
        new(
            "Be",
            ["be", "ru", "uk"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'be' and 2 other languages.</summary>
                /// <remarks>
                /// Shared by be, ru, uk.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class BeProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n % 10 = 1 and n % 100 != 11
                        if ((n % 10) == 1 && (n % 100) != 11)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: n % 10 = 2..4 and n % 100 != 12..14
                        if (((n % 10).IsInt() && (n % 10).IsBetween(2, 4)) && !(((n % 100).IsInt() && (n % 100).IsBetween(12, 14))))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n % 10 = 0 or n % 10 = 5..9 or n % 100 = 11..14
                        if ((n % 10) == 0 || ((n % 10).IsInt() && (n % 10).IsBetween(5, 9)) || ((n % 100).IsInt() && (n % 100).IsBetween(11, 14)))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // blo, cv, ksh
        new(
            "Blo",
            ["blo", "cv", "ksh"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'blo' and 2 other languages.</summary>
                /// <remarks>
                /// Shared by blo, cv, ksh.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class BloProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // zero: n = 0
                        if (n == 0)
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // bm, bo, dz, hnj, id, ig, ii, in, ja, jbo, jv, jw, kde, kea, km, ko, lkt, lo, ms, my, nqo, osa, sah, ses, sg, su, th, to, tpi, und, vi, wo, yo, yue, zh
        new(
            "Bm",
            ["bm", "bo", "dz", "hnj", "id", "ig", "ii", "in", "ja", "jbo", "jv", "jw", "kde", "kea", "km", "ko", "lkt", "lo", "ms", "my", "nqo", "osa", "sah", "ses", "sg", "su", "th", "to", "tpi", "und", "vi", "wo", "yo", "yue", "zh"],
            [PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'bm' and 34 other languages.</summary>
                /// <remarks>
                /// Shared by bm, bo, dz, hnj, id, ig, ii, in, ja, jbo, jv, jw, kde, kea, km, ko, lkt, lo, ms, my, nqo, osa, sah, ses, sg, su, th, to, tpi, und, vi, wo, yo, yue, zh.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class BmProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // br
        new(
            "Br",
            ["br"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'br'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class BrProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n % 10 = 1 and n % 100 != 11,71,91
                        if ((n % 10) == 1 && !(((n % 100) == 11 || (n % 100) == 71 || (n % 100) == 91)))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n % 10 = 2 and n % 100 != 12,72,92
                        if ((n % 10) == 2 && !(((n % 100) == 12 || (n % 100) == 72 || (n % 100) == 92)))
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n % 10 = 3..4,9 and n % 100 != 10..19,70..79,90..99
                        if (((n % 10).IsInt() && ((n % 10).IsBetween(3, 4) || (n % 10) == 9)) && !(((n % 100).IsInt() && ((n % 100).IsBetween(10, 19) || (n % 100).IsBetween(70, 79) || (n % 100).IsBetween(90, 99)))))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n != 0 and n % 1000000 = 0
                        if (n != 0 && (n % 1000000) == 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // bs, hr, sh, sr
        new(
            "Bs",
            ["bs", "hr", "sh", "sr"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'bs' and 3 other languages.</summary>
                /// <remarks>
                /// Shared by bs, hr, sh, sr.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class BsProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();
                        double f = n.DigitsAfterDecimal();

                        // one: v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11
                        if (v == 0 && (i % 10) == 1 && (i % 100) != 11 || (f % 10) == 1 && (f % 100) != 11)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: v = 0 and i % 10 = 2..4 and i % 100 != 12..14 or f % 10 = 2..4 and f % 100 != 12..14
                        if (v == 0 && (i % 10).IsBetween(2, 4) && !((i % 100).IsBetween(12, 14)) || (f % 10).IsBetween(2, 4) && !((f % 100).IsBetween(12, 14)))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ca, es, it, lld, pt-PT, scn, vec
        new(
            "Ca",
            ["ca", "es", "it", "lld", "pt-PT", "scn", "vec"],
            [PluralCategory.One, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ca' and 6 other languages.</summary>
                /// <remarks>
                /// Shared by ca, es, it, lld, pt-PT, scn, vec.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class CaProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 1 and v = 0
                        if (i == 1 && v == 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // many: e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
                        if (i != 0 && (i % 1000000) == 0 && v == 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ceb, fil, tl
        new(
            "Ceb",
            ["ceb", "fil", "tl"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ceb' and 2 other languages.</summary>
                /// <remarks>
                /// Shared by ceb, fil, tl.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class CebProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();
                        double f = n.DigitsAfterDecimal();

                        // one: v = 0 and i = 1,2,3 or v = 0 and i % 10 != 4,6,9 or v != 0 and f % 10 != 4,6,9
                        if (v == 0 && (i == 1 || i == 2 || i == 3) || v == 0 && !(((i % 10) == 4 || (i % 10) == 6 || (i % 10) == 9)) || v != 0 && !(((f % 10) == 4 || (f % 10) == 6 || (f % 10) == 9)))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // cs, sk
        new(
            "Cs",
            ["cs", "sk"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'cs' and 1 other language.</summary>
                /// <remarks>
                /// Shared by cs, sk.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class CsProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 1 and v = 0
                        if (i == 1 && v == 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: i = 2..4 and v = 0
                        if (i.IsBetween(2, 4) && v == 0)
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: v != 0
                        if (v != 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // cy
        new(
            "Cy",
            ["cy"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'cy'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class CyProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // zero: n = 0
                        if (n == 0)
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n = 3
                        if (n == 3)
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n = 6
                        if (n == 6)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // da
        new(
            "Da",
            ["da"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'da'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class DaProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double t = n.DigitsAfterDecimal();

                        // one: n = 1 or t != 0 and i = 0,1
                        if (n == 1 || t != 0 && (i == 0 || i == 1))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // dsb, hsb
        new(
            "Dsb",
            ["dsb", "hsb"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'dsb' and 1 other language.</summary>
                /// <remarks>
                /// Shared by dsb, hsb.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class DsbProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();
                        double f = n.DigitsAfterDecimal();

                        // one: v = 0 and i % 100 = 1 or f % 100 = 1
                        if (v == 0 && (i % 100) == 1 || (f % 100) == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: v = 0 and i % 100 = 2 or f % 100 = 2
                        if (v == 0 && (i % 100) == 2 || (f % 100) == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: v = 0 and i % 100 = 3..4 or f % 100 = 3..4
                        if (v == 0 && (i % 100).IsBetween(3, 4) || (f % 100).IsBetween(3, 4))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ff, hy, kab
        new(
            "Ff",
            ["ff", "hy", "kab"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ff' and 2 other languages.</summary>
                /// <remarks>
                /// Shared by ff, hy, kab.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class FfProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);

                        // one: i = 0,1
                        if (i == 0 || i == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // fr, pt
        new(
            "Fr",
            ["fr", "pt"],
            [PluralCategory.One, PluralCategory.Many, PluralCategory.Other],
            [PluralCategory.Many],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'fr' and 1 other language.</summary>
                /// <remarks>
                /// Shared by fr, pt.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class FrProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 0,1
                        if (i == 0 || i == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // many: e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5
                        if (i != 0 && (i % 1000000) == 0 && v == 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // ga
        new(
            "Ga",
            ["ga"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'ga'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class GaProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n = 3..6
                        if (n.IsInt() && n.IsBetween(3, 6))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n = 7..10
                        if (n.IsInt() && n.IsBetween(7, 10))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // gd
        new(
            "Gd",
            ["gd"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'gd'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class GdProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 1,11
                        if (n == 1 || n == 11)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2,12
                        if (n == 2 || n == 12)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n = 3..10,13..19
                        if (n.IsInt() && (n.IsBetween(3, 10) || n.IsBetween(13, 19)))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // gv
        new(
            "Gv",
            ["gv"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'gv'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class GvProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: v = 0 and i % 10 = 1
                        if (v == 0 && (i % 10) == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: v = 0 and i % 10 = 2
                        if (v == 0 && (i % 10) == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: v = 0 and i % 100 = 0,20,40,60,80
                        if (v == 0 && ((i % 100) == 0 || (i % 100) == 20 || (i % 100) == 40 || (i % 100) == 60 || (i % 100) == 80))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: v != 0
                        if (v != 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // he, iw
        new(
            "He",
            ["he", "iw"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'he' and 1 other language.</summary>
                /// <remarks>
                /// Shared by he, iw.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class HeProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 1 and v = 0 or i = 0 and v != 0
                        if (i == 1 && v == 0 || i == 0 && v != 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: i = 2 and v = 0
                        if (i == 2 && v == 0)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // is, mk
        new(
            "Is",
            ["is", "mk"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'is' and 1 other language.</summary>
                /// <remarks>
                /// Shared by is, mk.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class IsProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double t = n.DigitsAfterDecimal();

                        // one: t = 0 and i % 10 = 1 and i % 100 != 11 or t % 10 = 1 and t % 100 != 11
                        if (t == 0 && (i % 10) == 1 && (i % 100) != 11 || (t % 10) == 1 && (t % 100) != 11)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // iu, naq, sat, se, sma, smi, smj, smn, sms
        new(
            "Iu",
            ["iu", "naq", "sat", "se", "sma", "smi", "smj", "smn", "sms"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'iu' and 8 other languages.</summary>
                /// <remarks>
                /// Shared by iu, naq, sat, se, sma, smi, smj, smn, sms.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class IuProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // kw
        new(
            "Kw",
            ["kw"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'kw'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class KwProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // zero: n = 0
                        if (n == 0)
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n % 100 = 2,22,42,62,82 or n % 1000 = 0 and n % 100000 = 1000..20000,40000,60000,80000 or n != 0 and n % 1000000 = 100000
                        if (((n % 100) == 2 || (n % 100) == 22 || (n % 100) == 42 || (n % 100) == 62 || (n % 100) == 82) || (n % 1000) == 0 && ((n % 100000).IsInt() && ((n % 100000).IsBetween(1000, 20000) || (n % 100000) == 40000 || (n % 100000) == 60000 || (n % 100000) == 80000)) || n != 0 && (n % 1000000) == 100000)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n % 100 = 3,23,43,63,83
                        if ((n % 100) == 3 || (n % 100) == 23 || (n % 100) == 43 || (n % 100) == 63 || (n % 100) == 83)
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n != 1 and n % 100 = 1,21,41,61,81
                        if (n != 1 && ((n % 100) == 1 || (n % 100) == 21 || (n % 100) == 41 || (n % 100) == 61 || (n % 100) == 81))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // lag
        new(
            "Lag",
            ["lag"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'lag'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class LagProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);

                        // zero: n = 0
                        if (n == 0)
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: i = 0,1 and n != 0
                        if ((i == 0 || i == 1) && n != 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // lt
        new(
            "Lt",
            ["lt"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'lt'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class LtProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double f = n.DigitsAfterDecimal();

                        // one: n % 10 = 1 and n % 100 != 11..19
                        if ((n % 10) == 1 && !(((n % 100).IsInt() && (n % 100).IsBetween(11, 19))))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: n % 10 = 2..9 and n % 100 != 11..19
                        if (((n % 10).IsInt() && (n % 10).IsBetween(2, 9)) && !(((n % 100).IsInt() && (n % 100).IsBetween(11, 19))))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: f != 0
                        if (f != 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // lv, prg
        new(
            "Lv",
            ["lv", "prg"],
            [PluralCategory.Zero, PluralCategory.One, PluralCategory.Other],
            [],
            false,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'lv' and 1 other language.</summary>
                /// <remarks>
                /// Shared by lv, prg.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class LvProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double v = n.GetNumberOfDigitsAfterDecimal();
                        double f = n.DigitsAfterDecimal();

                        // zero: n % 10 = 0 or n % 100 = 11..19 or v = 2 and f % 100 = 11..19
                        if ((n % 10) == 0 || ((n % 100).IsInt() && (n % 100).IsBetween(11, 19)) || v == 2 && (f % 100).IsBetween(11, 19))
                        {
                            return PluralTypeEnum.ZERO;
                        }

                        // one: n % 10 = 1 and n % 100 != 11 or v = 2 and f % 10 = 1 and f % 100 != 11 or v != 2 and f % 10 = 1
                        if ((n % 10) == 1 && (n % 100) != 11 || v == 2 && (f % 10) == 1 && (f % 100) != 11 || v != 2 && (f % 10) == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // mo, ro
        new(
            "Mo",
            ["mo", "ro"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'mo' and 1 other language.</summary>
                /// <remarks>
                /// Shared by mo, ro.
                /// <para>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </para>
                /// </remarks>
                internal sealed class MoProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 1 and v = 0
                        if (i == 1 && v == 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: v != 0 or n = 0 or n != 1 and n % 100 = 1..19
                        if (v != 0 || n == 0 || n != 1 && ((n % 100).IsInt() && (n % 100).IsBetween(1, 19)))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // mt
        new(
            "Mt",
            ["mt"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'mt'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class MtProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 1
                        if (n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n = 0 or n % 100 = 3..10
                        if (n == 0 || ((n % 100).IsInt() && (n % 100).IsBetween(3, 10)))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: n % 100 = 11..19
                        if ((n % 100).IsInt() && (n % 100).IsBetween(11, 19))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // pl
        new(
            "Pl",
            ["pl"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'pl'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class PlProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: i = 1 and v = 0
                        if (i == 1 && v == 0)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: v = 0 and i % 10 = 2..4 and i % 100 != 12..14
                        if (v == 0 && (i % 10).IsBetween(2, 4) && !((i % 100).IsBetween(12, 14)))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14
                        if (v == 0 && i != 1 && (i % 10).IsBetween(0, 1) || v == 0 && (i % 10).IsBetween(5, 9) || v == 0 && (i % 100).IsBetween(12, 14))
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // sgs
        new(
            "Sgs",
            ["sgs"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Many, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'sgs'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class SgsProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double f = n.DigitsAfterDecimal();

                        // one: n % 10 = 1 and n % 100 != 11
                        if ((n % 10) == 1 && (n % 100) != 11)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: n = 2
                        if (n == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: n != 2 and n % 10 = 2..9 and n % 100 != 11..19
                        if (n != 2 && ((n % 10).IsInt() && (n % 10).IsBetween(2, 9)) && !(((n % 100).IsInt() && (n % 100).IsBetween(11, 19))))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        // many: f != 0
                        if (f != 0)
                        {
                            return PluralTypeEnum.MANY;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // shi
        new(
            "Shi",
            ["shi"],
            [PluralCategory.One, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'shi'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class ShiProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);

                        // one: i = 0 or n = 1
                        if (i == 0 || n == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // few: n = 2..10
                        if (n.IsInt() && n.IsBetween(2, 10))
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // si
        new(
            "Si",
            ["si"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'si'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class SiProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double f = n.DigitsAfterDecimal();

                        // one: n = 0,1 or i = 0 and f = 1
                        if ((n == 0 || n == 1) || i == 0 && f == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // sl
        new(
            "Sl",
            ["sl"],
            [PluralCategory.One, PluralCategory.Two, PluralCategory.Few, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'sl'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class SlProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        double i = System.Math.Truncate(n);
                        double v = n.GetNumberOfDigitsAfterDecimal();

                        // one: v = 0 and i % 100 = 1
                        if (v == 0 && (i % 100) == 1)
                        {
                            return PluralTypeEnum.ONE;
                        }

                        // two: v = 0 and i % 100 = 2
                        if (v == 0 && (i % 100) == 2)
                        {
                            return PluralTypeEnum.TWO;
                        }

                        // few: v = 0 and i % 100 = 3..4 or v != 0
                        if (v == 0 && (i % 100).IsBetween(3, 4) || v != 0)
                        {
                            return PluralTypeEnum.FEW;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
        // tzm
        new(
            "Tzm",
            ["tzm"],
            [PluralCategory.One, PluralCategory.Other],
            [],
            true,
            """
            using _ReswPlus_AutoGenerated.Utils;

            namespace _ReswPlus_AutoGenerated.Plurals
            {
                /// <summary>The plural rules Unicode CLDR 48 publishes for 'tzm'.</summary>
                /// <remarks>
                /// The condition quoted above each branch is the rule as CLDR publishes it, in the plural rule
                /// syntax of UTS #35: https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
                /// </remarks>
                internal sealed class TzmProvider : IPluralProvider
                {
                    public PluralTypeEnum ComputePlural(double n)
                    {
                        // one: n = 0..1 or n = 11..99
                        if ((n.IsInt() && n.IsBetween(0, 1)) || (n.IsInt() && n.IsBetween(11, 99)))
                        {
                            return PluralTypeEnum.ONE;
                        }

                        return PluralTypeEnum.OTHER;
                    }
                }
            }
            """),
    ];
}
