using System.Collections.Generic;
using System.Text;

namespace ReswPlus.SourceGenerator.ClassGenerators;

/// <summary>
/// Builds the body of the selector that maps a language tag to the provider holding its plural rules.
/// </summary>
/// <remarks>
/// The generated selector is a <c>switch</c> the runtime falls out of when nothing matches, so that the caller
/// can shorten the tag and look again. It carries no default branch for that reason: a default would match on
/// the first pass and stop a tag such as <c>pt-BR</c> from ever reaching the rules of <c>pt</c>.
/// </remarks>
internal static class PluralSelector
{
    /// <summary>
    /// Builds the cases of the selector.
    /// </summary>
    /// <param name="mappings">Each language tag and the identifier of the provider holding its rules.</param>
    /// <returns>The cases, ready to be substituted into the template.</returns>
    public static string Build(IEnumerable<(string LanguageTag, string ProviderId)> mappings)
    {
        var cases = new StringBuilder();
        var byProvider = new Dictionary<string, List<string>>();
        var order = new List<string>();

        foreach (var (languageTag, providerId) in mappings)
        {
            if (!byProvider.TryGetValue(providerId, out var tags))
            {
                byProvider[providerId] = tags = [];
                order.Add(providerId);
            }

            tags.Add(PluralFormsRetriever.NormalizeTag(languageTag));
        }

        foreach (var providerId in order)
        {
            foreach (var tag in byProvider[providerId])
            {
                cases.Append("case \"").Append(tag).Append("\":\n");
            }

            cases.Append("  return new _ReswPlus_AutoGenerated.Plurals.").Append(providerId).Append("Provider();\n");
        }

        return cases.ToString();
    }
}
