using System.Collections.Generic;
using System.Text;

namespace ReswPlus.SourceGenerator.ClassGenerators;

/// <summary>
/// Builds the selector that maps a language tag to the provider holding its plural rules.
/// </summary>
/// <remarks>
/// The generated selector is a <c>switch</c> the runtime falls out of when nothing matches, so that the caller
/// can shorten the tag and look again. It carries no default branch for that reason: a default would match on
/// the first pass and stop a tag such as <c>pt-BR</c> from ever reaching the rules of <c>pt</c>.
/// <para>
/// The <c>switch</c> itself is written here rather than in the template, because a project whose languages
/// have no rules of their own produces no cases at all, and an empty <c>switch</c> block is a warning.
/// </para>
/// </remarks>
internal static class PluralSelector
{
    /// <summary>
    /// The indentation the selector sits at inside the generated method.
    /// </summary>
    private const string Indent = "                ";

    /// <summary>
    /// Builds the selector.
    /// </summary>
    /// <param name="mappings">Each language tag and the identifier of the provider holding its rules.</param>
    /// <returns>The selector, ready to be substituted into the template, or an empty string when there is
    /// nothing to select between.</returns>
    public static string Build(IEnumerable<(string LanguageTag, string ProviderId)> mappings)
    {
        var byProvider = new Dictionary<string, List<string>>();
        var order = new List<string>();

        foreach (var (languageTag, providerId) in mappings)
        {
            if (!byProvider.TryGetValue(providerId, out var tags))
            {
                byProvider[providerId] = tags = [];
                order.Add(providerId);
            }

            tags.Add(PluralFormsRetriever.NormalizeTag(languageTag));
        }

        if (order.Count == 0)
        {
            return string.Empty;
        }

        var selector = new StringBuilder();

        selector.Append(Indent).AppendLine("switch (culture)");
        selector.Append(Indent).AppendLine("{");

        foreach (var providerId in order)
        {
            foreach (var tag in byProvider[providerId])
            {
                selector.Append(Indent).Append("    case \"").Append(tag).AppendLine("\":");
            }

            selector.Append(Indent).Append("        return new _ReswPlus_AutoGenerated.Plurals.")
                .Append(providerId).AppendLine("Provider();");
        }

        selector.Append(Indent).AppendLine("}");

        return selector.ToString();
    }
}
