<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\nuget\ReswPlus.SourceGenerator.NugetPackage.props" Condition="'$(Configuration)' == 'Release'" />
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
		<IsRoslynComponent>true</IsRoslynComponent>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <InternalsVisibleTo Include="ReswPlusUnitTests" />
      <InternalsVisibleTo Include="CldrRuleImporter" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="Templates\ResourceStringProviders\WindowsResourceStringProvider.txt" />
      <EmbeddedResource Include="Templates\ResourceStringProviders\MicrosoftResourceStringProvider.txt" />
      <EmbeddedResource Include="Templates\Macros\Macros.txt" />
      <EmbeddedResource Include="Templates\Plurals\ResourceLoaderExtension.txt" />
      <EmbeddedResource Include="Templates\Utils\DoubleExt.txt" />
      <EmbeddedResource Include="Templates\Utils\IntExt.txt" />
      <EmbeddedResource Include="Templates\Plurals\IPluralProvider.txt" />
      <EmbeddedResource Include="Templates\Plurals\PluralTypeEnum.txt" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    </ItemGroup>
    <Import Project="..\ReswPlus.Shared\ReswPlus.Shared.projitems" Label="Shared" />
</Project>
